#pragma once

enum Type{VERB, NOUN, ADVERB, ADJECTIVE, PRONOUN, PREPOSITION, CONJUNCTION, DETERMINER};
enum nType{BOY, GIRL, NON, GROUP, PLACE, THING, SELF, CONCRETE, NOTN};
enum propType{};
enum aType{HOW, WHERE, WHEN, MUCH, OFTEN, NOTA};
enum ajType{LOOKS, SIZE, COLOR, SOUNDS, FEEL, NOTAJ};
enum vType{STATE, TRANSITIVE, INTRANSITIVE, AUXILIARY, MODAL, ACTION, NOTV};
enum proType{SUBJECT, OBJECT, POSSESSIVEADJ, POSSESSIVEPRO, REFLEXIVE, NOTPRO};
enum prepType{TIME, LOCATION, DIRECTION, AGENT, INSTRUMENTS, PHRASES, NOTPREP};
enum conjType{COORDINATING, SUBORDINATING, CORRELATIVE, NOTC};
enum detType{ARTICLE, DEMONSTRATIVE, POSSESSIVE, QUANTIFIER, NUMBER, PRE, NOTD};

enum Presence{PAST, PRESENT, FUTURE, NOTP};
enum Person{FIRST, SECOND, THIRD, NOTPERS};

enum Function{SIGMOID, LRELU, TANH, RELU};
